CREATE DATABASE IF NOT EXISTS seattle_search;
USE seattle_search;

CREATE TABLE IF NOT EXISTS seattle_places (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(150) NOT NULL,
  slug VARCHAR(170) NOT NULL UNIQUE,
  category VARCHAR(80) NOT NULL,
  neighborhood VARCHAR(120) NOT NULL,
  summary TEXT NOT NULL,
  description TEXT NOT NULL,
  address VARCHAR(255) NOT NULL,
  keywords TEXT,
  url VARCHAR(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(190) NOT NULL UNIQUE,
  password_hash CHAR(64) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
