USE seattle_search;

DELETE FROM seattle_places;

INSERT INTO seattle_places
  (title, slug, category, neighborhood, summary, description, address, keywords, url)
VALUES
  (
    'Space Needle',
    'space-needle',
    'Landmark',
    'Seattle Center',
    'Ikon observasi Seattle dengan pemandangan 360 derajat kota, Elliott Bay, dan pegunungan.',
    'Space Needle adalah landmark paling terkenal di Seattle. Pengunjung datang untuk melihat panorama skyline, Puget Sound, dan Mount Rainier pada hari yang cerah.',
    '400 Broad St, Seattle, WA 98109',
    'observation deck, skyline, tourist attraction, seattle center, tower',
    'https://www.spaceneedle.com'
  ),
  (
    'Pike Place Market',
    'pike-place-market',
    'Market',
    'Downtown',
    'Pasar publik bersejarah dengan hasil laut segar, kios lokal, dan street performance.',
    'Pike Place Market menjadi pusat kuliner dan budaya lokal Seattle. Tempat ini terkenal dengan penjual ikan, toko kecil independen, dan akses mudah ke waterfront.',
    '85 Pike St, Seattle, WA 98101',
    'farmers market, seafood, local shops, downtown, tourism',
    'https://www.pikeplacemarket.org'
  ),
  (
    'Seattle Waterfront',
    'seattle-waterfront',
    'Attraction',
    'Waterfront',
    'Kawasan tepi laut dengan dermaga, restoran seafood, dan akses ferry.',
    'Seattle Waterfront menawarkan pengalaman berjalan santai di sepanjang Elliott Bay, dekat dengan akuarium, dermaga wisata, dan terminal ferry ke Bainbridge Island.',
    'Alaskan Way, Seattle, WA 98101',
    'elliott bay, ferry, seafood, promenade, pier',
    'https://waterfrontseattle.org'
  ),
  (
    'Museum of Pop Culture',
    'museum-of-pop-culture',
    'Museum',
    'Seattle Center',
    'Museum interaktif tentang musik, film, game, dan budaya populer.',
    'Museum of Pop Culture atau MoPOP memiliki pameran yang berganti-ganti tentang science fiction, musik Seattle, video game, dan tokoh budaya pop dunia.',
    '325 5th Ave N, Seattle, WA 98109',
    'mopop, music, sci-fi, exhibits, culture',
    'https://www.mopop.org'
  ),
  (
    'Discovery Park',
    'discovery-park',
    'Park',
    'Magnolia',
    'Taman terbesar di Seattle dengan jalur hiking, tebing, dan pantai.',
    'Discovery Park cocok untuk pencarian tentang alam Seattle. Area ini memiliki loop trail, pemandangan Puget Sound, habitat satwa, dan mercusuar West Point.',
    '3801 Discovery Park Blvd, Seattle, WA 98199',
    'hiking, nature, beach, magnolia, lighthouse',
    'https://www.seattle.gov/parks/allparks/discovery-park'
  ),
  (
    'Capitol Hill',
    'capitol-hill',
    'Neighborhood',
    'Capitol Hill',
    'Distrik trendi dengan kafe, kehidupan malam, seni, dan komunitas kreatif.',
    'Capitol Hill dikenal sebagai kawasan dinamis dengan restoran independen, toko vinyl, bar, mural, dan ruang komunitas. Cocok bagi pencari hiburan malam dan budaya lokal.',
    'Capitol Hill, Seattle, WA',
    'nightlife, cafes, arts, restaurants, music scene',
    'https://visitseattle.org/neighborhoods/capitol-hill'
  ),
  (
    'Ballard Locks',
    'ballard-locks',
    'Attraction',
    'Ballard',
    'Sistem kanal dan pintu air dengan taman botani dan fish ladder.',
    'Hiram M. Chittenden Locks menghubungkan Puget Sound dan Lake Washington. Pengunjung bisa menonton kapal lewat, melihat salmon migration, dan menikmati taman yang rapi.',
    '3015 NW 54th St, Seattle, WA 98107',
    'locks, canal, salmon ladder, boats, garden',
    'https://www.nws.usace.army.mil/Locations/Seattle-District/Locks/'
  ),
  (
    'Seattle Public Library Central Branch',
    'seattle-public-library-central-branch',
    'Library',
    'Downtown',
    'Perpustakaan modern dengan arsitektur ikonik dan ruang baca luas.',
    'Gedung perpustakaan pusat Seattle dirancang dengan bentuk geometris khas dan menjadi destinasi populer untuk belajar, bekerja, atau menikmati desain arsitektur kontemporer.',
    '1000 4th Ave, Seattle, WA 98104',
    'books, architecture, study space, downtown, rem koolhaas',
    'https://www.spl.org'
  ),
  (
    'University of Washington',
    'university-of-washington',
    'Campus',
    'University District',
    'Kampus riset besar dengan cherry blossoms dan akses ke distrik mahasiswa.',
    'University of Washington di Seattle terkenal karena Suzzallo Library, area kampus hijau, serta musim bunga sakura di The Quad yang menarik banyak pengunjung.',
    '1410 NE Campus Pkwy, Seattle, WA 98195',
    'college, campus, cherry blossoms, research, university district',
    'https://www.washington.edu'
  ),
  (
    'Seattle Japanese Garden',
    'seattle-japanese-garden',
    'Garden',
    'Madison Park',
    'Taman tenang dengan lanskap tradisional Jepang di dalam Washington Park Arboretum.',
    'Seattle Japanese Garden menawarkan pengalaman santai dengan kolam koi, jembatan, pohon mapel, dan desain lanskap yang berubah cantik sepanjang musim.',
    '1075 Lake Washington Blvd E, Seattle, WA 98112',
    'zen garden, koi pond, arboretum, seasonal garden, peaceful',
    'https://www.seattlejapanesegarden.org'
  ),
  (
    'Seattle Transit',
    'seattle-transit',
    'Transport',
    'Citywide',
    'Informasi umum tentang light rail, bus, streetcar, dan ferry di Seattle.',
    'Sistem transportasi Seattle mencakup Link light rail, King County Metro bus, Seattle Streetcar, dan Washington State Ferries. Pencarian ini membantu pengguna menemukan opsi mobilitas dalam kota.',
    'Seattle, WA',
    'link light rail, metro bus, public transit, ferry, commuting',
    'https://www.soundtransit.org'
  ),
  (
    'Seattle Coffee Culture',
    'seattle-coffee-culture',
    'Food & Drink',
    'Citywide',
    'Ringkasan budaya kopi Seattle dari kafe independen hingga roastery terkenal.',
    'Seattle punya identitas kuat dalam budaya kopi. Selain jaringan besar, kota ini dipenuhi specialty cafe, roastery lokal, dan ruang kerja santai untuk komunitas kreatif.',
    'Seattle, WA',
    'coffee shops, espresso, cafe, roastery, specialty coffee',
    'https://visitseattle.org'
  ),
  (
    'Chihuly Garden and Glass',
    'chihuly-garden-and-glass',
    'Museum',
    'Seattle Center',
    'Pameran kaca artistik dengan instalasi warna-warni dekat Space Needle.',
    'Chihuly Garden and Glass menampilkan karya Dale Chihuly dengan galeri indoor, glasshouse dramatis, dan taman patung kaca yang menjadi favorit wisatawan.',
    '305 Harrison St, Seattle, WA 98109',
    'glass art, dale chihuly, exhibition, seattle center, museum',
    'https://www.chihulygardenandglass.com'
  ),
  (
    'Seattle Art Museum',
    'seattle-art-museum',
    'Museum',
    'Downtown',
    'Museum seni utama Seattle dengan koleksi global dan pameran temporer.',
    'Seattle Art Museum berada di pusat kota dan menawarkan koleksi seni modern, kontemporer, Afrika, Asia, dan Native American dengan kurasi bergantian sepanjang tahun.',
    '1300 1st Ave, Seattle, WA 98101',
    'art museum, downtown, contemporary art, exhibitions, culture',
    'https://www.seattleartmuseum.org'
  ),
  (
    'Olympic Sculpture Park',
    'olympic-sculpture-park',
    'Park',
    'Belltown',
    'Taman tepi laut dengan instalasi seni besar dan jalur pejalan kaki.',
    'Olympic Sculpture Park milik Seattle Art Museum memadukan ruang hijau, pemandangan Puget Sound, dan patung skala besar dalam area terbuka yang gratis dikunjungi.',
    '2901 Western Ave, Seattle, WA 98121',
    'sculpture park, waterfront park, public art, belltown, outdoor museum',
    'https://www.seattleartmuseum.org/visit/olympic-sculpture-park'
  ),
  (
    'Kerry Park',
    'kerry-park',
    'Viewpoint',
    'Queen Anne',
    'Spot foto klasik untuk panorama skyline Seattle dan Space Needle.',
    'Kerry Park adalah salah satu viewpoint paling terkenal di Seattle, populer saat matahari terbenam karena menyajikan pemandangan kota, Elliott Bay, dan Mount Rainier.',
    '211 W Highland Dr, Seattle, WA 98119',
    'skyline view, queen anne, photo spot, sunset, mount rainier',
    'https://www.seattle.gov/parks/allparks/kerry-park'
  ),
  (
    'Gas Works Park',
    'gas-works-park',
    'Park',
    'Wallingford',
    'Taman unik bekas pabrik gas dengan bukit pandang ke Lake Union.',
    'Gas Works Park menawarkan ruang piknik, area festival, dan panorama downtown Seattle dari seberang danau. Struktur industrial lamanya menjadi ciri visual yang khas.',
    '2101 N Northlake Way, Seattle, WA 98103',
    'lake union, picnic, kite hill, industrial park, skyline view',
    'https://www.seattle.gov/parks/allparks/gas-works-park-and-play-barn'
  ),
  (
    'Green Lake Park',
    'green-lake-park',
    'Park',
    'Green Lake',
    'Danau kota populer untuk jogging, kayak, dan aktivitas keluarga.',
    'Green Lake Park memiliki jalur melingkar yang ramai dipakai warga untuk berlari, berjalan santai, bersepeda, dan menikmati olahraga air ringan.',
    '7201 E Green Lake Dr N, Seattle, WA 98115',
    'running trail, lake, kayaking, family park, outdoor recreation',
    'https://www.seattle.gov/parks/allparks/green-lake-park'
  ),
  (
    'Woodland Park Zoo',
    'woodland-park-zoo',
    'Zoo',
    'Phinney Ridge',
    'Kebun binatang besar dengan habitat modern dan program konservasi.',
    'Woodland Park Zoo menjadi tujuan keluarga populer di Seattle dengan koleksi satwa global, area edukasi, dan desain habitat yang meniru lingkungan asli hewan.',
    '5500 Phinney Ave N, Seattle, WA 98103',
    'animals, family attraction, wildlife, conservation, kids',
    'https://www.zoo.org'
  ),
  (
    'Seattle Aquarium',
    'seattle-aquarium',
    'Aquarium',
    'Waterfront',
    'Akuarium tepi laut dengan fokus pada ekosistem Puget Sound.',
    'Seattle Aquarium menampilkan kehidupan laut Pacific Northwest, termasuk otter laut, tide pool, dan edukasi konservasi yang relevan dengan perairan Seattle.',
    '1483 Alaskan Way, Seattle, WA 98101',
    'marine life, otters, waterfront, puget sound, family attraction',
    'https://www.seattleaquarium.org'
  ),
  (
    'T-Mobile Park',
    't-mobile-park',
    'Sports',
    'SoDo',
    'Stadion baseball Seattle Mariners dengan atap retraksi.',
    'T-Mobile Park adalah rumah bagi Seattle Mariners dan dikenal dengan pengalaman menonton baseball, pemandangan kota, serta pilihan makanan stadion yang kuat.',
    '1250 1st Ave S, Seattle, WA 98134',
    'baseball, mariners, stadium, sodo, sports venue',
    'https://www.mlb.com/mariners/ballpark'
  ),
  (
    'Lumen Field',
    'lumen-field',
    'Sports',
    'SoDo',
    'Stadion NFL dan MLS untuk Seahawks dan Sounders.',
    'Lumen Field adalah venue olahraga utama Seattle yang terkenal dengan atmosfer suporter yang sangat bising, terutama pada pertandingan Seahawks dan Sounders.',
    '800 Occidental Ave S, Seattle, WA 98134',
    'seahawks, sounders, football, soccer, stadium',
    'https://www.lumenfield.com'
  ),
  (
    'Fremont Troll',
    'fremont-troll',
    'Public Art',
    'Fremont',
    'Patung troll besar di bawah jembatan yang menjadi ikon unik Seattle.',
    'Fremont Troll adalah karya seni publik yang sangat dikenal dan sering muncul dalam itinerary wisata karena tampilannya yang unik dan lokasi fotogenik.',
    'N 36th St, Aurora Ave N, Seattle, WA 98103',
    'troll statue, public art, photo spot, fremont, quirky seattle',
    'https://fremont.com/explore/sights/fremont-troll/'
  ),
  (
    'Fremont Sunday Market',
    'fremont-sunday-market',
    'Market',
    'Fremont',
    'Pasar akhir pekan dengan vintage, makanan jalanan, dan produk lokal.',
    'Fremont Sunday Market menghadirkan pengalaman belanja santai dengan barang antik, fashion independen, kerajinan, dan berbagai pilihan makanan dari vendor lokal.',
    '3401 Evanston Ave N, Seattle, WA 98103',
    'weekend market, vintage, food trucks, handmade, local vendors',
    'https://www.fremontsundaymarket.com'
  ),
  (
    'Seattle Great Wheel',
    'seattle-great-wheel',
    'Attraction',
    'Waterfront',
    'Bianglala besar di waterfront dengan pemandangan Elliott Bay.',
    'Seattle Great Wheel menjadi salah satu atraksi visual utama di tepi laut dan menawarkan pengalaman melihat kota dari gondola tertutup.',
    '1301 Alaskan Way, Seattle, WA 98101',
    'ferris wheel, waterfront, observation, family attraction, elliott bay',
    'https://seattlegreatwheel.com'
  ),
  (
    'Benaroya Hall',
    'benaroya-hall',
    'Music Venue',
    'Downtown',
    'Rumah Seattle Symphony dengan akustik konser kelas dunia.',
    'Benaroya Hall adalah pusat pertunjukan musik klasik di downtown Seattle dan juga menjadi lokasi event budaya lain sepanjang tahun.',
    '200 University St, Seattle, WA 98101',
    'seattle symphony, concert hall, classical music, downtown, performance',
    'https://www.seattlesymphony.org/benaroya'
  ),
  (
    'Seattle Center Monorail',
    'seattle-center-monorail',
    'Transport',
    'Downtown',
    'Monorail ikonik yang menghubungkan Westlake Center dan Seattle Center.',
    'Seattle Center Monorail adalah bagian sejarah transportasi Seattle sejak World’s Fair 1962 dan masih menjadi opsi cepat untuk wisatawan menuju Space Needle area.',
    '370 Thomas St, Seattle, WA 98109',
    'monorail, seattle center, westlake, transit, world fair',
    'https://www.seattlemonorail.com'
  ),
  (
    'Washington State Ferries to Bainbridge',
    'washington-state-ferries-bainbridge',
    'Transport',
    'Waterfront',
    'Rute ferry populer dari Seattle ke Bainbridge Island.',
    'Ferry dari Seattle Waterfront ke Bainbridge Island menjadi salah satu perjalanan singkat paling populer untuk melihat skyline Seattle dari air.',
    '801 Alaskan Way, Seattle, WA 98104',
    'bainbridge ferry, washington state ferries, waterfront terminal, skyline cruise, commuter',
    'https://wsdot.wa.gov/travel/washington-state-ferries'
  ),
  (
    'International District',
    'international-district',
    'Neighborhood',
    'International District',
    'Kawasan budaya Asia dengan restoran, toko, dan sejarah komunitas imigran.',
    'International District atau Chinatown-International District dikenal karena dim sum, ramen, pasar Asia, museum komunitas, dan akses transit yang kuat.',
    'International District, Seattle, WA',
    'chinatown, asian food, dim sum, cultural district, historic neighborhood',
    'https://visitseattle.org/neighborhoods/chinatown-international-district'
  ),
  (
    'West Seattle Alki Beach',
    'west-seattle-alki-beach',
    'Beach',
    'West Seattle',
    'Pantai kota populer untuk sunset, sepeda, dan pemandangan skyline.',
    'Alki Beach memberikan suasana santai dengan jalur tepi laut, restoran kasual, dan pemandangan balik ke pusat kota Seattle di seberang Elliott Bay.',
    '1702 Alki Ave SW, Seattle, WA 98116',
    'beach walk, sunset, biking, west seattle, skyline view',
    'https://www.seattle.gov/parks/allparks/alki-beach-park'
  ),
  (
    'Golden Gardens Park',
    'golden-gardens-park',
    'Park',
    'Ballard',
    'Taman pantai populer untuk piknik, voli, dan matahari terbenam.',
    'Golden Gardens Park adalah salah satu tempat terbaik di Seattle untuk menikmati sore di tepi air, lengkap dengan area pasir, jalur pendek, dan pemandangan Olympic Mountains.',
    '8498 Seaview Pl NW, Seattle, WA 98117',
    'sunset beach, picnic, volleyball, ballard, puget sound',
    'https://www.seattle.gov/parks/allparks/golden-gardens-park'
  ),
  (
    'Volunteer Park Conservatory',
    'volunteer-park-conservatory',
    'Garden',
    'Capitol Hill',
    'Konservatori kaca bersejarah dengan koleksi tanaman tropis dan kaktus.',
    'Volunteer Park Conservatory menjadi destinasi tenang di Capitol Hill bagi pengunjung yang tertarik pada tanaman eksotis, arsitektur kaca klasik, dan suasana santai.',
    '1400 E Galer St, Seattle, WA 98112',
    'greenhouse, botanic collection, capitol hill, historic conservatory, plants',
    'https://www.volunteerparkconservatory.org'
  ),
  (
    'The Museum of Flight',
    'the-museum-of-flight',
    'Museum',
    'Georgetown',
    'Museum aviasi besar dengan pesawat bersejarah dan pameran antariksa.',
    'The Museum of Flight cocok untuk pencarian tentang pesawat, NASA, sejarah penerbangan, dan edukasi keluarga dengan koleksi yang sangat lengkap.',
    '9404 E Marginal Way S, Seattle, WA 98108',
    'aviation, airplanes, nasa, aerospace, family museum',
    'https://www.museumofflight.org'
  ),
  (
    'Pacific Science Center',
    'pacific-science-center',
    'Science Center',
    'Seattle Center',
    'Pusat sains interaktif dengan IMAX, planetarium, dan aktivitas keluarga.',
    'Pacific Science Center menghadirkan eksperimen langsung, pameran sains populer, area untuk anak, dan program pendidikan yang ramai dikunjungi.',
    '200 2nd Ave N, Seattle, WA 98109',
    'science museum, imax, planetarium, family activities, seattle center',
    'https://www.pacificsciencecenter.org'
  ),
  (
    'Amazon Spheres',
    'amazon-spheres',
    'Architecture',
    'South Lake Union',
    'Kompleks kubah kaca ikonik di kawasan kantor Amazon.',
    'Amazon Spheres dikenal karena desain futuristik dan koleksi tanaman indoor yang besar. Area South Lake Union di sekitarnya juga populer untuk kafe dan restoran.',
    '2111 7th Ave, Seattle, WA 98121',
    'amazon campus, glass domes, architecture, south lake union, urban design',
    'https://www.seattlespheres.com'
  ),
  (
    'South Lake Union Streetcar',
    'south-lake-union-streetcar',
    'Transport',
    'South Lake Union',
    'Layanan streetcar yang melayani koridor South Lake Union ke downtown.',
    'South Lake Union Streetcar membantu mobilitas menuju area perkantoran, restoran, dan hotel di kawasan teknologi Seattle.',
    'Westlake Ave N, Seattle, WA',
    'streetcar, public transit, tech district, downtown connection, south lake union',
    'https://kingcounty.gov/en/dept/metro/routes-and-service/schedules-and-maps/streetcar'
  ),
  (
    'Seattle Underground Tour',
    'seattle-underground-tour',
    'Tour',
    'Pioneer Square',
    'Tur sejarah bawah tanah tentang awal perkembangan kota Seattle.',
    'Underground Tour di Pioneer Square membawa pengunjung ke lorong-lorong bawah permukaan kota lama dan menjadi salah satu pengalaman sejarah paling khas di Seattle.',
    '614 1st Ave, Seattle, WA 98104',
    'history tour, pioneer square, underground city, walking tour, seattle history',
    'https://www.undergroundtour.com'
  ),
  (
    'Pioneer Square',
    'pioneer-square',
    'Neighborhood',
    'Pioneer Square',
    'Distrik bersejarah dengan galeri seni, bangunan bata, dan tur kota lama.',
    'Pioneer Square adalah salah satu kawasan tertua Seattle, terkenal dengan arsitektur romanesque, galeri First Thursday, dan akses mudah ke stadion.',
    'Pioneer Square, Seattle, WA',
    'historic district, art galleries, brick buildings, first thursday, old seattle',
    'https://visitseattle.org/neighborhoods/pioneer-square'
  ),
  (
    'Ballard Brewery District',
    'ballard-brewery-district',
    'Food & Drink',
    'Ballard',
    'Kawasan brewery craft beer yang populer di Seattle utara.',
    'Ballard Brewery District menarik pencari minuman lokal, taproom, dan suasana santai akhir pekan dengan banyak pilihan craft beer dalam area yang mudah dijelajahi.',
    'Ballard, Seattle, WA',
    'craft beer, taproom, brewery trail, nightlife, ballard',
    'https://visitseattle.org/neighborhoods/ballard'
  ),
  (
    'U District Farmers Market',
    'u-district-farmers-market',
    'Market',
    'University District',
    'Pasar petani populer dengan produk segar dan vendor makanan lokal.',
    'U District Farmers Market dikenal sebagai salah satu farmers market terbaik di Seattle dengan hasil tani regional, bakery, dan siap santap.',
    '5031 University Way NE, Seattle, WA 98105',
    'farmers market, fresh produce, local food, university district, weekend market',
    'https://seattlefarmersmarkets.org/udfm'
  ),
  (
    'Seattle Central Library Events',
    'seattle-central-library-events',
    'Library',
    'Downtown',
    'Program baca, diskusi, dan event komunitas di perpustakaan pusat Seattle.',
    'Selain arsitekturnya yang terkenal, Seattle Central Library juga sering menjadi lokasi event komunitas, workshop, dan program literasi untuk publik.',
    '1000 4th Ave, Seattle, WA 98104',
    'library events, community programs, reading, workshops, downtown',
    'https://www.spl.org/event-calendar'
  ),
  (
    'Seattle Food Trucks',
    'seattle-food-trucks',
    'Food & Drink',
    'Citywide',
    'Ringkasan pencarian food truck populer di berbagai kawasan Seattle.',
    'Food truck Seattle hadir di area kantor, festival, brewery, dan market dengan menu mulai dari taco, burger, hingga fusion Asia.',
    'Seattle, WA',
    'street food, food trucks, lunch spots, casual eats, local vendors',
    'https://www.seattlefoodtruck.com'
  ),
  (
    'Seattle Live Music',
    'seattle-live-music',
    'Music Venue',
    'Citywide',
    'Panduan pencarian venue live music, indie show, dan scene lokal Seattle.',
    'Seattle memiliki sejarah musik kuat dari grunge hingga indie modern. Query ini mencakup venue kecil, konser lokal, dan kawasan dengan kehidupan musik aktif.',
    'Seattle, WA',
    'concerts, indie venues, grunge history, local bands, nightlife',
    'https://visitseattle.org'
  ),
  (
    'Seattle Tech Scene',
    'seattle-tech-scene',
    'Business',
    'South Lake Union',
    'Ringkasan area teknologi, startup, dan kantor besar di Seattle.',
    'Seattle Tech Scene mencakup South Lake Union, Downtown, dan Bellevue area yang terkait dengan startup, cloud computing, e-commerce, serta coworking space.',
    'South Lake Union, Seattle, WA',
    'startups, amazon, microsoft ecosystem, coworking, innovation',
    'https://www.greaterseattle.org'
  ),
  (
    'Seattle Rainy Day Ideas',
    'seattle-rainy-day-ideas',
    'Travel Guide',
    'Citywide',
    'Kumpulan ide indoor saat hujan di Seattle seperti museum, kopi, dan library.',
    'Karena cuaca Seattle sering identik dengan hujan, pencarian ini membantu pengguna menemukan aktivitas indoor nyaman untuk solo traveler, keluarga, atau pasangan.',
    'Seattle, WA',
    'rainy day, indoor activities, museums, cafes, family itinerary',
    'https://visitseattle.org'
  ),
  (
    'Seattle Family Activities',
    'seattle-family-activities',
    'Travel Guide',
    'Citywide',
    'Panduan aktivitas keluarga di Seattle dari zoo hingga science center.',
    'Seattle Family Activities membantu pencarian destinasi ramah anak seperti aquarium, zoo, taman, museum interaktif, dan ruang terbuka keluarga.',
    'Seattle, WA',
    'kids activities, family trip, aquarium, zoo, educational attractions',
    'https://visitseattle.org'
  ),
  (
    'Seattle Hiking Day Trips',
    'seattle-hiking-day-trips',
    'Outdoor',
    'Citywide',
    'Ide pencarian hiking dan day trip alam dari basis kota Seattle.',
    'Banyak pengunjung menggunakan Seattle sebagai titik awal untuk hiking ringan, scenic drive, dan perjalanan sehari ke pegunungan atau pulau di sekitar Puget Sound.',
    'Seattle, WA',
    'day trips, hiking, mountains, scenic drive, outdoor adventure',
    'https://www.wta.org'
  );
